# Generated by Django 5.2.13 on 2026-04-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
